### ISSUE TITLE
Posting comment multiple times

### ISSUE THREAD

**Issue by klippx** [lucassabreu/comment-coverage-clover#35]
https://github.com/lucassabreu/comment-coverage-clover/blob/main/CHANGELOG.md#001---2021-08-15
According to v0.0.1 (initial release) this action should not post multiple comments on the same PR.

Yet, it posts a new comment on every push. I expected it to keep it to 1 comment and keep that one comment updated instead.

Is this a regression?

Example:
<img width="345" alt="Screenshot 2023-05-24 at 16 25 04" src="https://github.com/lucassabreu/comment-coverage-clover/assets/2785359/122e7947-8a2c-482f-aaac-581573b10b6d">

**Comment by lucassabreu** [comment]
hi @klippx were you able to test it with the newest version?

**Comment by lucassabreu** [comment]
i am thinking that it may be related to the custom github token from a real account; 

when the action looks for the previous comment it filter for comments from bots;

since the comments on the print do not tag the tag; then it does not find them.

![image](https://github.com/lucassabreu/comment-coverage-clover/assets/3457213/aea9cf40-2e05-4177-8fc5-d243e5f10967)

i will look into filtering the comments from the same account; not just from a bot.

**Comment by lucassabreu** [comment]
hi @klippx the new release ([v0.10.0](https://github.com/lucassabreu/comment-coverage-clover/releases/tag/v0.10.0)) should resolve the problem with using a PAT for the comments.

could you try it and report if it fits your case?

**Comment by lucassabreu** [comment]
(you may need to delete the older comments yourself first)

**Comment by klippx** [comment]
It seems to work now! 💅
